---
- hosts: all
  become: true
  roles:
    - set_hostname
    - disable_firewall
    - update_system
- hosts: k8s_nodes
  become: true
  roles:
    - disable_selinux
- hosts: k8s_nodes
  become: true
  roles:
    - keepalived_install
    - keepalived_k8s_api
    - haproxy_config
    - k8s_prereqs
    - k8s_init
