---
- hosts: all
  become: true
  roles:
    - set_hostname
    - disable_firewall
    - update_system
- hosts: k8s_nodes
  become: true
  roles:
    - disable_selinux
- hosts: k8s_nodes
  become: true
  roles:
    - keepalived_install
    - keepalived_k8s_api
    - haproxy_config
    - k8s_prereqs
    - k8s_init
    - cilium_install
    - metrics-server_install
    - istio_install
    - longhorn_install
    - metallb_install
    - cert-manager_install
    - external-dns_install
- hosts: k8s_init_node
  become: true
  vars_prompt:
    - name: pihole_password
      prompt: Enter pihole password
      private: false
  roles:
    - pihole_install
    - monitoring_install
